// Copyright (c) 2023 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMyEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyEnergyRequest) Reset() {
	*x = GetMyEnergyRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyEnergyRequest) ProtoMessage() {}

func (x *GetMyEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyEnergyRequest.ProtoReflect.Descriptor instead.
func (*GetMyEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMyEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type ConsumeMyEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                          // Energy to consume
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // Type: plant, harvest, visit, craft, explore, special
	ActionId      string                 `protobuf:"bytes,4,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`       // Optional specific action ID for analytics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeMyEnergyRequest) Reset() {
	*x = ConsumeMyEnergyRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeMyEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeMyEnergyRequest) ProtoMessage() {}

func (x *ConsumeMyEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeMyEnergyRequest.ProtoReflect.Descriptor instead.
func (*ConsumeMyEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumeMyEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConsumeMyEnergyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsumeMyEnergyRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ConsumeMyEnergyRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type RefillMyEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Energy to add
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                                    // Source: purchase, reward, levelup, daily, ad_watch, gift
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                      // Item ID if source is 'purchase'
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Transaction ID for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefillMyEnergyRequest) Reset() {
	*x = RefillMyEnergyRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefillMyEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillMyEnergyRequest) ProtoMessage() {}

func (x *RefillMyEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillMyEnergyRequest.ProtoReflect.Descriptor instead.
func (*RefillMyEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefillMyEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RefillMyEnergyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefillMyEnergyRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RefillMyEnergyRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RefillMyEnergyRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetMyEnergyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyEnergyConfigRequest) Reset() {
	*x = GetMyEnergyConfigRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyEnergyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyEnergyConfigRequest) ProtoMessage() {}

func (x *GetMyEnergyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyEnergyConfigRequest.ProtoReflect.Descriptor instead.
func (*GetMyEnergyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetMyEnergyConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetMyInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyInventoryRequest) Reset() {
	*x = GetMyInventoryRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyInventoryRequest) ProtoMessage() {}

func (x *GetMyInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetMyInventoryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMyInventoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyRequest) Reset() {
	*x = GetEnergyRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyRequest) ProtoMessage() {}

func (x *GetEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyRequest.ProtoReflect.Descriptor instead.
func (*GetEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConsumeEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                          // Energy to consume
	ActionType    string                 `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // Type: plant, harvest, visit, craft, explore, special
	ActionId      string                 `protobuf:"bytes,5,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`       // Optional specific action ID for analytics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeEnergyRequest) Reset() {
	*x = ConsumeEnergyRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyRequest) ProtoMessage() {}

func (x *ConsumeEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyRequest.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConsumeEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumeEnergyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsumeEnergyRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ConsumeEnergyRequest) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

type RefillEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                   // Energy to add
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`                                    // Source: purchase, reward, levelup, daily, ad_watch, gift
	ItemId        string                 `protobuf:"bytes,5,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`                      // Item ID if source is 'purchase'
	TransactionId string                 `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Transaction ID for validation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefillEnergyRequest) Reset() {
	*x = RefillEnergyRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefillEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillEnergyRequest) ProtoMessage() {}

func (x *RefillEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillEnergyRequest.ProtoReflect.Descriptor instead.
func (*RefillEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *RefillEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RefillEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefillEnergyRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefillEnergyRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RefillEnergyRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RefillEnergyRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetEnergyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyConfigRequest) Reset() {
	*x = GetEnergyConfigRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyConfigRequest) ProtoMessage() {}

func (x *GetEnergyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyConfigRequest.ProtoReflect.Descriptor instead.
func (*GetEnergyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetEnergyConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetEnergyConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateEnergyConfigRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MaxEnergy        int32                  `protobuf:"varint,3,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`                        // New max energy (optional, 0 = no change)
	RegenRateSeconds int32                  `protobuf:"varint,4,opt,name=regen_rate_seconds,json=regenRateSeconds,proto3" json:"regen_rate_seconds,omitempty"` // New regen rate in seconds (optional, 0 = no change)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEnergyConfigRequest) Reset() {
	*x = UpdateEnergyConfigRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnergyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnergyConfigRequest) ProtoMessage() {}

func (x *UpdateEnergyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnergyConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnergyConfigRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEnergyConfigRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateEnergyConfigRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEnergyConfigRequest) GetMaxEnergy() int32 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *UpdateEnergyConfigRequest) GetRegenRateSeconds() int32 {
	if x != nil {
		return x.RegenRateSeconds
	}
	return 0
}

type ResetEnergyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEnergyRequest) Reset() {
	*x = ResetEnergyRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEnergyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnergyRequest) ProtoMessage() {}

func (x *ResetEnergyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnergyRequest.ProtoReflect.Descriptor instead.
func (*ResetEnergyRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *ResetEnergyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResetEnergyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyState   *EnergyState           `protobuf:"bytes,1,opt,name=energy_state,json=energyState,proto3" json:"energy_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyResponse) Reset() {
	*x = GetEnergyResponse{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyResponse) ProtoMessage() {}

func (x *GetEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyResponse.ProtoReflect.Descriptor instead.
func (*GetEnergyResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetEnergyResponse) GetEnergyState() *EnergyState {
	if x != nil {
		return x.EnergyState
	}
	return nil
}

type ConsumeEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyState   *EnergyState           `protobuf:"bytes,1,opt,name=energy_state,json=energyState,proto3" json:"energy_state,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Loot          []*LootItem            `protobuf:"bytes,4,rep,name=loot,proto3" json:"loot,omitempty"` // Loot earned from this action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeEnergyResponse) Reset() {
	*x = ConsumeEnergyResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeEnergyResponse) ProtoMessage() {}

func (x *ConsumeEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeEnergyResponse.ProtoReflect.Descriptor instead.
func (*ConsumeEnergyResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeEnergyResponse) GetEnergyState() *EnergyState {
	if x != nil {
		return x.EnergyState
	}
	return nil
}

func (x *ConsumeEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeEnergyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConsumeEnergyResponse) GetLoot() []*LootItem {
	if x != nil {
		return x.Loot
	}
	return nil
}

// Loot item dropped from an action
type LootItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LootItem) Reset() {
	*x = LootItem{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LootItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LootItem) ProtoMessage() {}

func (x *LootItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LootItem.ProtoReflect.Descriptor instead.
func (*LootItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *LootItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *LootItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *LootItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type RefillEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyState   *EnergyState           `protobuf:"bytes,1,opt,name=energy_state,json=energyState,proto3" json:"energy_state,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefillEnergyResponse) Reset() {
	*x = RefillEnergyResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefillEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillEnergyResponse) ProtoMessage() {}

func (x *RefillEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillEnergyResponse.ProtoReflect.Descriptor instead.
func (*RefillEnergyResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *RefillEnergyResponse) GetEnergyState() *EnergyState {
	if x != nil {
		return x.EnergyState
	}
	return nil
}

func (x *RefillEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefillEnergyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEnergyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *EnergyConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEnergyConfigResponse) Reset() {
	*x = GetEnergyConfigResponse{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEnergyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEnergyConfigResponse) ProtoMessage() {}

func (x *GetEnergyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEnergyConfigResponse.ProtoReflect.Descriptor instead.
func (*GetEnergyConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetEnergyConfigResponse) GetConfig() *EnergyConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*InventoryItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetInventoryResponse) GetItems() []*InventoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// Item in player's inventory
type InventoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *InventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateEnergyConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *EnergyConfig          `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnergyConfigResponse) Reset() {
	*x = UpdateEnergyConfigResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnergyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnergyConfigResponse) ProtoMessage() {}

func (x *UpdateEnergyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnergyConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnergyConfigResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEnergyConfigResponse) GetConfig() *EnergyConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateEnergyConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateEnergyConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetEnergyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnergyState   *EnergyState           `protobuf:"bytes,1,opt,name=energy_state,json=energyState,proto3" json:"energy_state,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetEnergyResponse) Reset() {
	*x = ResetEnergyResponse{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetEnergyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetEnergyResponse) ProtoMessage() {}

func (x *ResetEnergyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetEnergyResponse.ProtoReflect.Descriptor instead.
func (*ResetEnergyResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ResetEnergyResponse) GetEnergyState() *EnergyState {
	if x != nil {
		return x.EnergyState
	}
	return nil
}

func (x *ResetEnergyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetEnergyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnergyState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentEnergy    int32                  `protobuf:"varint,2,opt,name=current_energy,json=currentEnergy,proto3" json:"current_energy,omitempty"`              // Current energy amount
	MaxEnergy        int32                  `protobuf:"varint,3,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`                          // Maximum energy capacity
	LastUpdateTime   int64                  `protobuf:"varint,4,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`         // Unix timestamp of last update
	RegenRateSeconds int32                  `protobuf:"varint,5,opt,name=regen_rate_seconds,json=regenRateSeconds,proto3" json:"regen_rate_seconds,omitempty"`   // Seconds per energy point
	NextRegenTime    int64                  `protobuf:"varint,6,opt,name=next_regen_time,json=nextRegenTime,proto3" json:"next_regen_time,omitempty"`            // Unix timestamp when next energy regenerates
	EnergyToMax      int32                  `protobuf:"varint,7,opt,name=energy_to_max,json=energyToMax,proto3" json:"energy_to_max,omitempty"`                  // Energy needed to reach max
	TimeToMaxSeconds int64                  `protobuf:"varint,8,opt,name=time_to_max_seconds,json=timeToMaxSeconds,proto3" json:"time_to_max_seconds,omitempty"` // Seconds until full
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnergyState) Reset() {
	*x = EnergyState{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyState) ProtoMessage() {}

func (x *EnergyState) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyState.ProtoReflect.Descriptor instead.
func (*EnergyState) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *EnergyState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnergyState) GetCurrentEnergy() int32 {
	if x != nil {
		return x.CurrentEnergy
	}
	return 0
}

func (x *EnergyState) GetMaxEnergy() int32 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *EnergyState) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *EnergyState) GetRegenRateSeconds() int32 {
	if x != nil {
		return x.RegenRateSeconds
	}
	return 0
}

func (x *EnergyState) GetNextRegenTime() int64 {
	if x != nil {
		return x.NextRegenTime
	}
	return 0
}

func (x *EnergyState) GetEnergyToMax() int32 {
	if x != nil {
		return x.EnergyToMax
	}
	return 0
}

func (x *EnergyState) GetTimeToMaxSeconds() int64 {
	if x != nil {
		return x.TimeToMaxSeconds
	}
	return 0
}

type EnergyConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MaxEnergy        int32                  `protobuf:"varint,2,opt,name=max_energy,json=maxEnergy,proto3" json:"max_energy,omitempty"`                        // Maximum energy capacity
	RegenRateSeconds int32                  `protobuf:"varint,3,opt,name=regen_rate_seconds,json=regenRateSeconds,proto3" json:"regen_rate_seconds,omitempty"` // Seconds per energy point
	Level            int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                                 // Energy system level
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnergyConfig) Reset() {
	*x = EnergyConfig{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnergyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnergyConfig) ProtoMessage() {}

func (x *EnergyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnergyConfig.ProtoReflect.Descriptor instead.
func (*EnergyConfig) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *EnergyConfig) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnergyConfig) GetMaxEnergy() int32 {
	if x != nil {
		return x.MaxEnergy
	}
	return 0
}

func (x *EnergyConfig) GetRegenRateSeconds() int32 {
	if x != nil {
		return x.RegenRateSeconds
	}
	return 0
}

func (x *EnergyConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aservice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"2\n" +
	"\x12GetMyEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x8c\x01\n" +
	"\x16ConsumeMyEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\taction_id\x18\x04 \x01(\tR\bactionId\"\xa5\x01\n" +
	"\x15RefillMyEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"8\n" +
	"\x18GetMyEnergyConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"5\n" +
	"\x15GetMyInventoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"I\n" +
	"\x10GetEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa3\x01\n" +
	"\x14ConsumeEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\taction_id\x18\x05 \x01(\tR\bactionId\"\xbc\x01\n" +
	"\x13RefillEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x17\n" +
	"\aitem_id\x18\x05 \x01(\tR\x06itemId\x12%\n" +
	"\x0etransaction_id\x18\x06 \x01(\tR\rtransactionId\"O\n" +
	"\x16GetEnergyConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9f\x01\n" +
	"\x19UpdateEnergyConfigRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"max_energy\x18\x03 \x01(\x05R\tmaxEnergy\x12,\n" +
	"\x12regen_rate_seconds\x18\x04 \x01(\x05R\x10regenRateSeconds\"K\n" +
	"\x12ResetEnergyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x11GetEnergyResponse\x127\n" +
	"\fenergy_state\x18\x01 \x01(\v2\x14.service.EnergyStateR\venergyState\"\xab\x01\n" +
	"\x15ConsumeEnergyResponse\x127\n" +
	"\fenergy_state\x18\x01 \x01(\v2\x14.service.EnergyStateR\venergyState\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12%\n" +
	"\x04loot\x18\x04 \x03(\v2\x11.service.LootItemR\x04loot\"\\\n" +
	"\bLootItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x83\x01\n" +
	"\x14RefillEnergyResponse\x127\n" +
	"\fenergy_state\x18\x01 \x01(\v2\x14.service.EnergyStateR\venergyState\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"H\n" +
	"\x17GetEnergyConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.service.EnergyConfigR\x06config\"D\n" +
	"\x14GetInventoryResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.service.InventoryItemR\x05items\"a\n" +
	"\rInventoryItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x7f\n" +
	"\x1aUpdateEnergyConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.service.EnergyConfigR\x06config\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x82\x01\n" +
	"\x13ResetEnergyResponse\x127\n" +
	"\fenergy_state\x18\x01 \x01(\v2\x14.service.EnergyStateR\venergyState\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xbf\x02\n" +
	"\vEnergyState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ecurrent_energy\x18\x02 \x01(\x05R\rcurrentEnergy\x12\x1d\n" +
	"\n" +
	"max_energy\x18\x03 \x01(\x05R\tmaxEnergy\x12(\n" +
	"\x10last_update_time\x18\x04 \x01(\x03R\x0elastUpdateTime\x12,\n" +
	"\x12regen_rate_seconds\x18\x05 \x01(\x05R\x10regenRateSeconds\x12&\n" +
	"\x0fnext_regen_time\x18\x06 \x01(\x03R\rnextRegenTime\x12\"\n" +
	"\renergy_to_max\x18\a \x01(\x05R\venergyToMax\x12-\n" +
	"\x13time_to_max_seconds\x18\b \x01(\x03R\x10timeToMaxSeconds\"\x8a\x01\n" +
	"\fEnergyConfig\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"max_energy\x18\x02 \x01(\x05R\tmaxEnergy\x12,\n" +
	"\x12regen_rate_seconds\x18\x03 \x01(\x05R\x10regenRateSeconds\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level2\xe5\x1a\n" +
	"\aService\x12\xae\x02\n" +
	"\vGetMyEnergy\x12\x1b.service.GetMyEnergyRequest\x1a\x1a.service.GetEnergyResponse\"\xe5\x01\x92A|\x12\rGet my energy\x1a]Get your current energy state. Automatically calculates regenerated energy since last update.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x02\x82\xd3\xe4\x93\x022\x120/v1/public/namespace/{namespace}/users/me/energy\x12\xba\x02\n" +
	"\x0fConsumeMyEnergy\x12\x1f.service.ConsumeMyEnergyRequest\x1a\x1e.service.ConsumeEnergyResponse\"\xe5\x01\x92Ax\x12\x11Consume my energy\x1aUDeduct energy for performing an in-game action. Returns error if insufficient energy.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x04\x82\xd3\xe4\x93\x026:\x01*\"1/v1/public/namespace/{namespace}/users/me/consume\x12\xb3\x02\n" +
	"\x0eRefillMyEnergy\x12\x1e.service.RefillMyEnergyRequest\x1a\x1d.service.RefillEnergyResponse\"\xe1\x01\x92Au\x12\x10Refill my energy\x1aSAdd energy to your pool. Used for purchases, rewards, level ups, and daily bonuses.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x04\x82\xd3\xe4\x93\x025:\x01*\"0/v1/public/namespace/{namespace}/users/me/refill\x12\x8e\x02\n" +
	"\x0eGetMyInventory\x12\x1e.service.GetMyInventoryRequest\x1a\x1d.service.GetInventoryResponse\"\xbc\x01\x92AP\x12\x10Get my inventory\x1a.Get your current inventory of collected items.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x02\x82\xd3\xe4\x93\x025\x123/v1/public/namespace/{namespace}/users/me/inventory\x12\x9d\x02\n" +
	"\x11GetMyEnergyConfig\x12!.service.GetMyEnergyConfigRequest\x1a .service.GetEnergyConfigResponse\"\xc2\x01\x92AY\x12\x14Get my energy config\x1a3Get your max energy and regeneration rate settings.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18&NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x02\x82\xd3\xe4\x93\x022\x120/v1/public/namespace/{namespace}/users/me/config\x12\xd0\x02\n" +
	"\tGetEnergy\x12\x19.service.GetEnergyRequest\x1a\x1a.service.GetEnergyResponse\"\x8b\x02\x92A\x94\x01\x12\x19[Admin] Get player energy\x1aiGet the current energy state for a player. Automatically calculates regenerated energy since last update.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x02\x82\xd3\xe4\x93\x029\x127/v1/admin/namespace/{namespace}/player/{user_id}/energy\x12\xbb\x02\n" +
	"\rConsumeEnergy\x12\x1d.service.ConsumeEnergyRequest\x1a\x1e.service.ConsumeEnergyResponse\"\xea\x01\x92Ap\x12\x1d[Admin] Consume player energy\x1aADeduct energy for a player. Returns error if insufficient energy.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02=:\x01*\"8/v1/admin/namespace/{namespace}/player/{user_id}/consume\x12\xcc\x02\n" +
	"\fRefillEnergy\x12\x1c.service.RefillEnergyRequest\x1a\x1d.service.RefillEnergyResponse\"\xfe\x01\x92A\x84\x01\x12\x1c[Admin] Refill player energy\x1aVAdd energy to a player's pool. Used for admin grants, corrections, or backend rewards.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02<:\x01*\"7/v1/admin/namespace/{namespace}/player/{user_id}/refill\x12\xba\x02\n" +
	"\x0fGetEnergyConfig\x12\x1f.service.GetEnergyConfigRequest\x1a .service.GetEnergyConfigResponse\"\xe3\x01\x92Am\x12 [Admin] Get player energy config\x1a;Get the player's max energy and regeneration rate settings.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x02\x82\xd3\xe4\x93\x029\x127/v1/admin/namespace/{namespace}/player/{user_id}/config\x12\xbb\x02\n" +
	"\x12UpdateEnergyConfig\x12\".service.UpdateEnergyConfigRequest\x1a#.service.UpdateEnergyConfigResponse\"\xdb\x01\x92Ab\x12#[Admin] Update player energy config\x1a-Update max energy or regen rate for a player.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\x04\x82\xd3\xe4\x93\x02<:\x01*\x1a7/v1/admin/namespace/{namespace}/player/{user_id}/config\x12\xa9\x02\n" +
	"\vResetEnergy\x12\x1b.service.ResetEnergyRequest\x1a\x1c.service.ResetEnergyResponse\"\xde\x01\x92Af\x12\x1b[Admin] Reset player energy\x1a9Reset a player's energy to default state. Admin use only.b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18,ADMIN:NAMESPACE:{namespace}:CLOUDSAVE:RECORD\x90\xb5\x18\b\x82\xd3\xe4\x93\x02;:\x01*\"6/v1/admin/namespace/{namespace}/player/{user_id}/resetB\xcb\x02\x92A\xdc\x01\x12\xa4\x01\n" +
	"\x12Energy Service API\x12\x88\x01Manages player energy for action-based gameplay. Classic mobile game energy system with regeneration, consumption, and refill mechanics.2\x031.0\"\x12/energy-based-gameZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"\"net.accelbyte.extend.energyserviceP\x01Z\"extend-custom-guild-service/pkg/pb\xaa\x02\x1eAccelByte.Extend.EnergyServiceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_service_proto_goTypes = []any{
	(*GetMyEnergyRequest)(nil),         // 0: service.GetMyEnergyRequest
	(*ConsumeMyEnergyRequest)(nil),     // 1: service.ConsumeMyEnergyRequest
	(*RefillMyEnergyRequest)(nil),      // 2: service.RefillMyEnergyRequest
	(*GetMyEnergyConfigRequest)(nil),   // 3: service.GetMyEnergyConfigRequest
	(*GetMyInventoryRequest)(nil),      // 4: service.GetMyInventoryRequest
	(*GetEnergyRequest)(nil),           // 5: service.GetEnergyRequest
	(*ConsumeEnergyRequest)(nil),       // 6: service.ConsumeEnergyRequest
	(*RefillEnergyRequest)(nil),        // 7: service.RefillEnergyRequest
	(*GetEnergyConfigRequest)(nil),     // 8: service.GetEnergyConfigRequest
	(*UpdateEnergyConfigRequest)(nil),  // 9: service.UpdateEnergyConfigRequest
	(*ResetEnergyRequest)(nil),         // 10: service.ResetEnergyRequest
	(*GetEnergyResponse)(nil),          // 11: service.GetEnergyResponse
	(*ConsumeEnergyResponse)(nil),      // 12: service.ConsumeEnergyResponse
	(*LootItem)(nil),                   // 13: service.LootItem
	(*RefillEnergyResponse)(nil),       // 14: service.RefillEnergyResponse
	(*GetEnergyConfigResponse)(nil),    // 15: service.GetEnergyConfigResponse
	(*GetInventoryResponse)(nil),       // 16: service.GetInventoryResponse
	(*InventoryItem)(nil),              // 17: service.InventoryItem
	(*UpdateEnergyConfigResponse)(nil), // 18: service.UpdateEnergyConfigResponse
	(*ResetEnergyResponse)(nil),        // 19: service.ResetEnergyResponse
	(*EnergyState)(nil),                // 20: service.EnergyState
	(*EnergyConfig)(nil),               // 21: service.EnergyConfig
}
var file_service_proto_depIdxs = []int32{
	20, // 0: service.GetEnergyResponse.energy_state:type_name -> service.EnergyState
	20, // 1: service.ConsumeEnergyResponse.energy_state:type_name -> service.EnergyState
	13, // 2: service.ConsumeEnergyResponse.loot:type_name -> service.LootItem
	20, // 3: service.RefillEnergyResponse.energy_state:type_name -> service.EnergyState
	21, // 4: service.GetEnergyConfigResponse.config:type_name -> service.EnergyConfig
	17, // 5: service.GetInventoryResponse.items:type_name -> service.InventoryItem
	21, // 6: service.UpdateEnergyConfigResponse.config:type_name -> service.EnergyConfig
	20, // 7: service.ResetEnergyResponse.energy_state:type_name -> service.EnergyState
	0,  // 8: service.Service.GetMyEnergy:input_type -> service.GetMyEnergyRequest
	1,  // 9: service.Service.ConsumeMyEnergy:input_type -> service.ConsumeMyEnergyRequest
	2,  // 10: service.Service.RefillMyEnergy:input_type -> service.RefillMyEnergyRequest
	4,  // 11: service.Service.GetMyInventory:input_type -> service.GetMyInventoryRequest
	3,  // 12: service.Service.GetMyEnergyConfig:input_type -> service.GetMyEnergyConfigRequest
	5,  // 13: service.Service.GetEnergy:input_type -> service.GetEnergyRequest
	6,  // 14: service.Service.ConsumeEnergy:input_type -> service.ConsumeEnergyRequest
	7,  // 15: service.Service.RefillEnergy:input_type -> service.RefillEnergyRequest
	8,  // 16: service.Service.GetEnergyConfig:input_type -> service.GetEnergyConfigRequest
	9,  // 17: service.Service.UpdateEnergyConfig:input_type -> service.UpdateEnergyConfigRequest
	10, // 18: service.Service.ResetEnergy:input_type -> service.ResetEnergyRequest
	11, // 19: service.Service.GetMyEnergy:output_type -> service.GetEnergyResponse
	12, // 20: service.Service.ConsumeMyEnergy:output_type -> service.ConsumeEnergyResponse
	14, // 21: service.Service.RefillMyEnergy:output_type -> service.RefillEnergyResponse
	16, // 22: service.Service.GetMyInventory:output_type -> service.GetInventoryResponse
	15, // 23: service.Service.GetMyEnergyConfig:output_type -> service.GetEnergyConfigResponse
	11, // 24: service.Service.GetEnergy:output_type -> service.GetEnergyResponse
	12, // 25: service.Service.ConsumeEnergy:output_type -> service.ConsumeEnergyResponse
	14, // 26: service.Service.RefillEnergy:output_type -> service.RefillEnergyResponse
	15, // 27: service.Service.GetEnergyConfig:output_type -> service.GetEnergyConfigResponse
	18, // 28: service.Service.UpdateEnergyConfig:output_type -> service.UpdateEnergyConfigResponse
	19, // 29: service.Service.ResetEnergy:output_type -> service.ResetEnergyResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
